# Generated by Django 4.2.3 on 2025-02-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Naziv"),
                ),
                (
                    "latin_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Latinski naziv"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="plant_images/",
                        verbose_name="Slika",
                    ),
                ),
                ("description", models.TextField(verbose_name="Opis")),
                ("drug", models.CharField(max_length=200, verbose_name="Droga")),
                ("indications", models.TextField(verbose_name="Indikacije")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Datum kreiranja"
                    ),
                ),
            ],
            options={
                "verbose_name": "Biljka",
                "verbose_name_plural": "Biljke",
                "ordering": ["name"],
            },
        ),
    ]
