# Generated by Django 4.2.3 on 2025-02-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PharmaFloraApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="plant", name="created_at",),
    ]
