# Generated by Django 4.2.3 on 2025-04-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PharmaFloraApp", "0002_remove_plant_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Naziv lokacije"),
                ),
                ("latitude", models.FloatField(verbose_name="Geografska širina")),
                ("longitude", models.FloatField(verbose_name="Geografska dužina")),
            ],
        ),
        migrations.AddField(
            model_name="plant",
            name="locations",
            field=models.ManyToManyField(
                blank=True, to="PharmaFloraApp.location", verbose_name="Lokaliteti"
            ),
        ),
    ]
