# Generated by Django 4.2.3 on 2025-04-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PharmaFloraApp", "0003_location_plant_locations"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("geojson", models.FileField(upload_to="regions_geojson/")),
            ],
        ),
        migrations.RemoveField(model_name="plant", name="locations",),
        migrations.DeleteModel(name="Location",),
        migrations.AddField(
            model_name="plant",
            name="regions",
            field=models.ManyToManyField(
                blank=True, related_name="plants", to="PharmaFloraApp.region"
            ),
        ),
    ]
