# Generated by Django 4.2.3 on 2025-04-17 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "PharmaFloraApp",
            "0004_region_remove_plant_locations_delete_location_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveCompound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Naziv supstance"),
                ),
                (
                    "mol_file",
                    models.FileField(upload_to="molecules/", verbose_name="MOL fajl"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Opis supstance"),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_compounds",
                        to="PharmaFloraApp.plant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aktivna supstanca",
                "verbose_name_plural": "Aktivne supstance",
            },
        ),
    ]
