# Generated by Django 4.2.3 on 2025-04-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PharmaFloraApp", "0005_activecompound"),
    ]

    operations = [
        migrations.AddField(
            model_name="activecompound",
            name="molecular_formula",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Molekulska formula"
            ),
        ),
        migrations.AddField(
            model_name="activecompound",
            name="solubility",
            field=models.CharField(
                blank=True,
                help_text="Rastvorljiv u vodi, Slabo rastvorljiv u vodi, Nerastvorljiv u vodi, Rastvorljiv u mastima, Slabo rastvorljiv u mastima, Nerastvorljiv u mastima, Amfipatski, Dobro rastvorljiv u alkoholu, Rastvorljiv u organskim rastvaračima",
                max_length=100,
                verbose_name="Rastvorljivost",
            ),
        ),
        migrations.AddField(
            model_name="activecompound",
            name="structure_class",
            field=models.CharField(
                blank=True,
                help_text="Alkaloidi, Flavonoidi, Terpeni, Saponini, Heterozidi, Kumarini, Tanini, Lignani, Stilbeni, Antracenski derivati, Poliacetileni, Steroli, Steroidni sapogenini, Kinoni, Fenilpropanoidi, Polifenoli, Gorke materije, Iridoidi, SekoIridoidi, Sluzne materije, Masne kiseline, Eterična ulja, Peptidi, Ciklični peptidi",
                max_length=100,
                verbose_name="Strukturna klasa",
            ),
        ),
    ]
