# Generated by Django 4.2.3 on 2025-04-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PharmaFloraApp", "0006_activecompound_molecular_formula_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activecompound",
            name="log_p",
            field=models.FloatField(
                blank=True,
                help_text="Unesite vrednost Log P (može biti decimalni broj).",
                null=True,
                verbose_name="Log P",
            ),
        ),
        migrations.AlterField(
            model_name="activecompound",
            name="solubility",
            field=models.TextField(
                blank=True,
                help_text="Unesite detaljan opis rastvorljivosti supstance, npr. u vodi, mastima, alkoholu, itd.",
                verbose_name="Rastvorljivost",
            ),
        ),
        migrations.AlterField(
            model_name="activecompound",
            name="structure_class",
            field=models.TextField(
                blank=True,
                help_text="Unesite detaljan opis strukturne klase supstance.",
                verbose_name="Strukturna klasa",
            ),
        ),
    ]
