# Generated by Django 4.2.3 on 2025-04-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "PharmaFloraApp",
            "0007_activecompound_log_p_alter_activecompound_solubility_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="activecompound",
            name="iupac_name",
            field=models.CharField(
                blank=True,
                help_text="Unesite IUPAC naziv supstance.",
                max_length=255,
                verbose_name="IUPAC naziv",
            ),
        ),
    ]
