# Generated by Django 4.2.3 on 2025-04-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PharmaFloraApp", "0008_activecompound_iupac_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="activecompound", name="plant",),
        migrations.AddField(
            model_name="activecompound",
            name="plants",
            field=models.ManyToManyField(
                related_name="active_compounds",
                to="PharmaFloraApp.plant",
                verbose_name="Biljke",
            ),
        ),
    ]
